install: 
language: swift
os: osx
osx_image: xcode12.2
script:
  xcodebuild -scheme SwiftGenius -destination 'platform=iOS Simulator,OS=14.2,name=iPhone 12 Pro' test
after_success:
  bash <(curl -s https://codecov.io/bash)

